<Project>

    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    </PropertyGroup>

    <ItemGroup>
        <!-- Preenchido conforme os projetos forem precisando -->
    </ItemGroup>

</Project>