<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="NSubstitute"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\server\TCMine.Server.Application\TCMine.Server.Application.csproj"/>
        <ProjectReference Include="..\..\src\server\TCMine.Server.Domain\TCMine.Server.Domain.csproj"/>
        <ProjectReference Include="..\..\src\server\TCMine.Server.Infrastructure\TCMine.Server.Infrastructure.csproj"/>
        <ProjectReference Include="..\..\src\shared\TCMine.Contracts\TCMine.Contracts.csproj"/>
    </ItemGroup>

</Project>
