// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCMine_Server.Infrastructure.Persistence;

#nullable disable

namespace TCMine_Server.Infrastructure.Migrations.Sqlite
{
    [DbContext(typeof(SqliteAppDbContext))]
    [Migration("20260703060433_DropPlayerConfigs")]
    partial class DropPlayerConfigs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("TCMine_Domain.Entities.ModFileEntity", b =>
                {
                    b.Property<long>("FileId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CurseModId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OrphanedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha1")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("FileId");

                    b.ToTable("ModFiles");
                });

            modelBuilder.Entity("TCMine_Domain.Entities.ModpackEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasOverrides")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Loader")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LoaderVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Minecraft")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecommendedRamMb")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Modpacks");
                });

            modelBuilder.Entity("TCMine_Domain.Entities.ModpackImportSourceEntity", b =>
                {
                    b.Property<Guid>("ModpackId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CurseProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurseProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("InstalledFileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstalledVersion")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LatestFileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LatestVersion")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("ModpackId");

                    b.ToTable("ModpackImportSources");
                });

            modelBuilder.Entity("TCMine_Domain.Entities.ModpackModEntity", b =>
                {
                    b.Property<Guid>("ModpackId")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("ModpackId", "FileId");

                    b.HasIndex("FileId");

                    b.ToTable("ModpackMods");
                });

            modelBuilder.Entity("TCMine_Domain.Entities.NewsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ModpackId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModpackId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("TCMine_Domain.Entities.OverrideHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actor")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentBefore")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModpackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PathAfter")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("PathBefore")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModpackId", "CreatedAt");

                    b.ToTable("OverrideHistory");
                });

            modelBuilder.Entity("TCMine_Domain.Entities.ReleaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Files")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("TCMine_Domain.Entities.ServerEntryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModpackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ServerInstanceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModpackId");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("TCMine_Domain.Entities.ServerInstanceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Advertise")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoRestart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Directory")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraJvmArgs")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageTag")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ModpackId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motd")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ProvisionedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RamMb")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("XmsMb")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModpackId");

                    b.ToTable("ServerInstances");
                });

            modelBuilder.Entity("TCMine_Domain.Entities.ServerRuntimeCacheEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Loader")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LoaderVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("MinecraftVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Loader", "LoaderVersion", "MinecraftVersion")
                        .IsUnique();

                    b.ToTable("ServerRuntimeCache");
                });

            modelBuilder.Entity("TCMine_Domain.Entities.ServerSettingEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AzureClientId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AzureTenantId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CfApiKeyEncrypted")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicBaseUrl")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("TCMine_Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TCMine_Domain.Entities.ModpackImportSourceEntity", b =>
                {
                    b.HasOne("TCMine_Domain.Entities.ModpackEntity", "Modpack")
                        .WithMany()
                        .HasForeignKey("ModpackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modpack");
                });

            modelBuilder.Entity("TCMine_Domain.Entities.ModpackModEntity", b =>
                {
                    b.HasOne("TCMine_Domain.Entities.ModFileEntity", "ModFile")
                        .WithMany("ModpackLinks")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TCMine_Domain.Entities.ModpackEntity", "Modpack")
                        .WithMany("Mods")
                        .HasForeignKey("ModpackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModFile");

                    b.Navigation("Modpack");
                });

            modelBuilder.Entity("TCMine_Domain.Entities.NewsEntity", b =>
                {
                    b.HasOne("TCMine_Domain.Entities.ModpackEntity", null)
                        .WithMany()
                        .HasForeignKey("ModpackId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TCMine_Domain.Entities.ServerEntryEntity", b =>
                {
                    b.HasOne("TCMine_Domain.Entities.ModpackEntity", "Modpack")
                        .WithMany("Servers")
                        .HasForeignKey("ModpackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modpack");
                });

            modelBuilder.Entity("TCMine_Domain.Entities.ServerInstanceEntity", b =>
                {
                    b.HasOne("TCMine_Domain.Entities.ModpackEntity", "Modpack")
                        .WithMany()
                        .HasForeignKey("ModpackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Modpack");
                });

            modelBuilder.Entity("TCMine_Domain.Entities.ModFileEntity", b =>
                {
                    b.Navigation("ModpackLinks");
                });

            modelBuilder.Entity("TCMine_Domain.Entities.ModpackEntity", b =>
                {
                    b.Navigation("Mods");

                    b.Navigation("Servers");
                });
#pragma warning restore 612, 618
        }
    }
}
